version: '3'
services:
    web: 
        ports:
            - "${PORT_PREFIX}0080:80"
    laravel:
        depends_on: 
            - dev_mysql
    phpunit:
        depends_on:
            - dev_mysql
    dev_mysql:
        image: mysql:8.0
        user: "${UID}"
        environment:
            - TZ=Asia/Tokyo
            - MYSQL_DATABASE=env
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/conf.d:/etc/mysql/conf.d
        ports:
            - "${PORT_PREFIX}3306:3306"
        networks: 
            - my_network
        restart: always
