version: '3'
services:
    web: 
        ports:
    artisan:
        depends_on: 
            - dev_mysql
            - "${PORT_PREFIX}0080:80"
    laravel:
        depends_on: 
            - dev_mysql
    phpunit:
        depends_on:
            - dev_mysql
    dev_mysql:
        build:
            context: ./
            dockerfile: ./mysql/Dockerfile
        user: "${UID}"
        environment:
            - TZ=Asia/Tokyo
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/conf.d:/etc/mysql/conf.d
        ports:
            - "${PORT_PREFIX}3306:3306"
        networks: 
            - my_network
        restart: always
